sources: 
  - name: gz_raw_data
    tables: 
      - name: sales
        identifier: ventes_brutes_gz
      - name: product
        identifier: produit_brut_gz
      - name: ship
        identifier: navire_gz_brut
